### ISSUE TITLE
File corrupt

### ISSUE THREAD

**Issue by DaveEOS** [adafruit/Adafruit-USB-LiIon-LiPoly-Charger-PCB#1]
Adafruit USB LiIon-LiPoly Charger.sch has some invalid unicode characters in line 65. From Eagle...

```EAGLE update report

Date: 2/1/18 10:58 PM
File: /Users/dave/code/adafruit/Adafruit-USB-LiIon-LiPoly-Charger-PCB/Adafruit USB LiIon-LiPoly Charger.sch

An error occurred while parsing the intermediate XML file.
The XML file has been loaded into a text editor window as
/Users/dave/code/adafruit/Adafruit-USB-LiIon-LiPoly-Charger-PCB/Adafruit USB LiIon-LiPoly Charger.rpt.sch

Error:

line 65, column 30: Unexpected ''.```

**Comment by ladyada** [comment]
just downloaded zip. opens fine in eagle! https://github.com/adafruit/Adafruit-USB-LiIon-LiPoly-Charger-PCB/archive/master.zip

**Comment by DaveEOS** [comment]
Thanks for checking. I've tried both the zip and the github raw. I'm on a Mac, so maybe there is an encoding difference. It's in the name of layer 88, a layer that looks empty anyway. Can you tell me what that is supposed to be?
<img width="587" alt="screen shot 2018-02-02 at 4 57 45 pm" src="https://user-images.githubusercontent.com/25374619/35761257-7d7ac5ba-083b-11e8-8b22-3aeec33cec67.png">
