### ISSUE TITLE
Unable to open file

### ISSUE THREAD

**Issue by aguileraGit** [adafruit/Adafruit-USB-LiIon-LiPoly-Charger-PCB#2]
I'm unable to open the schematic file using Eagle 9.4.2.

**Comment by ladyada** [comment]
just tried & it works fine, you may not be cloning or downloading correctly

**Comment by aguileraGit** [comment]
Could be.

```
<layer number="56" name="wert" color="7" fill="1" visible="yes" active="yes"/>
<layer number="88" name="·S1ÀLÿLöè	ÿ" color="9" fill="1" visible="yes" active="yes"/>
<layer number="89" name="SimProbes" color="9" fill="1" visible="yes" active="yes"/>
```

I'll try again. Thanks!

**Comment by aguileraGit** [comment]
@ladyada Nope. Tried downloading again and cloning. Also, check out #1 . Same issue. Could be Mac related.

**Comment by aguileraGit** [comment]
I think the either the *name* for *layer number="88"* is blank or has a strange character which causes problems. Maybe only in Macs.

Here's how I fixed it.
1. Open in Eagle. It fails. Copy the xml file it loads.
2. Open in Atom or your favorite editor. Look at Line 65 or search for 'layer number="88". 
3. Delete that line and save the file.
4. Copy the original brd file next to the newly saved sch file and name the same.
5. Open in Eagle.

**Comment by ladyada** [comment]
huh can you submit a PR to fix?

**Comment by DAugusteDataTip** [comment]
Same problem on Mac, here, fixed using the steps above.
